---
title: "STAT 131 Final Project"
author: "Mina Lee, Isha Vaish, Tom Zhang"
date: "2023-04-20"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(astsa)
require(knitr)
library(ggplot2)
library(zoo)
library(TSA)
library(tidyverse)
library(MuMIn)
```


# Part 1. Dataset Exploration

```{r}
# import the data
ds <- read.csv('options_KR.csv')
head(ds)
```

```{r}
# check the trend of KOSPI 200 & VCOSPI
kospi <- ds$KOSPI200
times <- as.Date(ds$Date)
vkospi <- ds$VKOSPI
```


```{r}
# check the trend of KOSPI 200 & VCOSPI
kospi <- ds$KOSPI200
times <- as.Date(ds$Date)
vkospi <- ds$VKOSPI
```


```{r}
# Plot original Times Series of KOSPI & VKOSPI
plot(kospi, type='l', col='red', main="KOSPI Time Series")
plot(vkospi, type='l',col='blue', main = "VKOSPI Time Series")
```

```{r}
# try Detrending & Differencing the data
# take the log
log_kospi <- log(kospi)
# take the residual and plot
check <- residuals(lm(log_kospi ~seq_along(log_kospi)))
plot(check, type='l', col='green', main='Detrended log of KOSPI')
plot(diff(check), type='l', col='blue',main='Differenced log of KOSPI')
```

```{r}
# Calculate Return 
KOSPI200_yesterday <- lag(kospi, n = 1)
return_array = (kospi-KOSPI200_yesterday) / KOSPI200_yesterday
```

```{r}
# This matches the differenced dataset
plot(return_array, type='l', main='Return of KOSPI200')
```



```{r}
Yt <- diff(check)

# Create the ACF plot of Yt
acf(Yt,  main = "ACF of Yt")

# Create the PACF plot of Yt
pacf(Yt,  main = "PACF of Yt")

# Create the EACF plot of Yt
eacf(Yt)
```

```{r}
# Perform the McLeod-Li test
# Compute squared returns
McLeod.Li.test(y=Yt)
```


```{r}
# Plot autocorrelation and partial autocorrelation of squared returns
r.Yt <- Yt^2
acf(r.Yt, lag.max = 30, main = "ACF of Squared Returns")
pacf(r.Yt, lag.max = 30, main = "PACF of Squared Returns")
```


```{r}
eacf(r.Yt)
eacf(abs(Yt))
```


